leecade/react-native-swiper

README.md, dist/index.js, examples/examples/index.js, examples/examples/phone.js, examples/examples/swiper.js, src/index.js
Hello,
Currently it is complicated to override easily controls (nextButton & prevButton).
If the looping is disable, we have to know the state of index, so, I suggest an improvement to avoid the knowing of state.index to override controls (nextButton and prevButton).
I updated the README accordingly my PR.
Best,
=> Improve the way to override controls buttons (nextButton & prevButton)

dist/index.js, examples/examples/dynamic.js, src/index.js
Adds support for dynamic children as well as an example.
=> Dynamic Swipables

src/index.js
fix warnings about keys for dots
=> fix warnings about keys for dots

examples/iOS/Info.plist, examples/node_modules/react-native/Libraries/ActionSheetIOS/RCTActionSheet.xcodeproj/xcuserdata/allomov.xcuserdatad/xcschemes/RCTActionSheet.xcscheme, examples/node_modules/react-native/Libraries/ActionSheetIOS/RCTActionSheet.xcodeproj/xcuserdata/allomov.xcuserdatad/xcschemes/xcschememanagement.plist, examples/node_modules/react-native/Libraries/AdSupport/RCTAdSupport.xcodeproj/xcuserdata/allomov.xcuserdatad/xcschemes/RCTAdSupport.xcscheme, examples/node_modules/react-native/Libraries/AdSupport/RCTAdSupport.xcodeproj/xcuserdata/allomov.xcuserdatad/xcschemes/xcschememanagement.plist, examples/node_modules/react-native/Libraries/GeoLocation/RCTGeolocation.xcodeproj/xcuserdata/allomov.xcuserdatad/xcschemes/RCTGeolocation.xcscheme, examples/node_modules/react-native/Libraries/GeoLocation/RCTGeolocation.xcodeproj/xcuserdata/allomov.xcuserdatad/xcschemes/xcschememanagement.plist, examples/node_modules/react-native/Libraries/Image/RCTImage.xcodeproj/xcuserdata/allomov.xcuserdatad/xcschemes/RCTImage.xcscheme, examples/node_modules/react-native/Libraries/Image/RCTImage.xcodeproj/xcuserdata/allomov.xcuserdatad/xcschemes/xcschememanagement.plist, examples/node_modules/react-native/Libraries/LinkingIOS/RCTLinking.xcodeproj/xcuserdata/allomov.xcuserdatad/xcschemes/RCTLinking.xcscheme, examples/node_modules/react-native/Libraries/LinkingIOS/RCTLinking.xcodeproj/xcuserdata/allomov.xcuserdatad/xcschemes/xcschememanagement.plist, examples/node_modules/react-native/Libraries/Network/RCTNetwork.xcodeproj/xcuserdata/allomov.xcuserdatad/xcschemes/RCTNetwork.xcscheme, examples/node_modules/react-native/Libraries/Network/RCTNetwork.xcodeproj/xcuserdata/allomov.xcuserdatad/xcschemes/xcschememanagement.plist, examples/node_modules/react-native/Libraries/RCTWebSocketDebugger/RCTWebSocketDebugger.xcodeproj/xcuserdata/allomov.xcuserdatad/xcschemes/RCTWebSocketDebugger.xcscheme, examples/node_modules/react-native/Libraries/RCTWebSocketDebugger/RCTWebSocketDebugger.xcodeproj/xcuserdata/allomov.xcuserdatad/xcschemes/xcschememanagement.plist, examples/node_modules/react-native/Libraries/Text/RCTText.xcodeproj/xcuserdata/allomov.xcuserdatad/xcschemes/RCTText.xcscheme, examples/node_modules/react-native/Libraries/Text/RCTText.xcodeproj/xcuserdata/allomov.xcuserdatad/xcschemes/xcschememanagement.plist, examples/node_modules/react-native/Libraries/Vibration/RCTVibration.xcodeproj/xcuserdata/allomov.xcuserdatad/xcschemes/RCTVibration.xcscheme, examples/node_modules/react-native/Libraries/Vibration/RCTVibration.xcodeproj/xcuserdata/allomov.xcuserdatad/xcschemes/xcschememanagement.plist, examples/node_modules/react-native/React/React.xcodeproj/xcuserdata/allomov.xcuserdatad/xcschemes/React.xcscheme, examples/node_modules/react-native/React/React.xcodeproj/xcuserdata/allomov.xcuserdatad/xcschemes/xcschememanagement.plist
Hey. Thank you for a good react-native code sample.
Today I wanted to run the example project on the latest xcode 7 with ios9 simulator and got some problems with it:
1. the app showed an exception about unsecured connection to development server on `localhost:8081`, and here is a discussion of this problem: https://github.com/facebook/react-native/issues/1563. 
1. Another problem appear to be connected with ios 9 and here is [a link to apple dev forum](https://forums.developer.apple.com/thread/13683).
=> Changes to make the example work in xcode 7

src/index.js
add simple support for android. No props handled yet.
=> add simple support for android

src/index.js
=> Fixing RN "no key" warning

dist/index.js, src/index.js
Thanks for this component
fix #95 #106 #79
=> fix deprecated scrollTo and fix android next-prev buttons

src/index.js
=> Don't attempt to mutate this.props

dist/index.js, src/index.js
Used the diff from the PR #165 by NightCatSama to make the necessary changes to src/index.js,
plus fixed an iOS bug introduced by NightCatSama changes.
Fixes #193 and #83
=> fixed loop and autoplay bugs in android

src/index.js
In this PR:
- "loadMinimal" added to prop API
- Only slides 1 before or after selected index are loaded, others have an empty View with ActivityLoader
=> add loadMinimal to api (lazyloading-esque)

examples/index.js, src/index.js
Hi! I just write an issue about this functionality (#219).
Will help me a lot if you can merge it.
Just added a custom prop to set the number of items loaded when loadMinimal is active.
=> #219: Add loadMinimalSize property

examples/components/SwiperNumber/index.js
fixes #242 . Can someone confirm that this works on iOS?
=> fix styling so that pagination example for android

README.md, src/index.js
This aims at adding a prop to customize user's experience.
Instead of displaying the plain `<ActivityIndicator />` we can now use our own react Element.
=> Add loadMinimalLoader prop

README.md
Hi there, 
First at all thanks for this repo, it´s been really helpful to me.
I noticed there are some issues regarding how to disable swiping, I though it would be a good idea to add it to the Readme so other could find it right away.
Hope it helps, 
Cheers
=> Added scrollEnabled prop to documentation

src/index.js
Just a Quick fix for an assumed typo that was causing errors in my App.
**Bug Reference Below*
=> fix for a bug/issue i was having when swiper looping from end to start

src/index.js
- Yes or No ? yes
- If yes, which issue (fix #number) ? Fix #507
- Yes or no ?
- remove non used var newInternals
=> Remove newInternals var

src/index.js
Bugfix for ViewPagerAndroid issue described [here](https://github.com/facebook/react-native/issues/13463#issuecomment-310896400)
=> Fix android issue with dynamically added children

.github/ISSUE_TEMPLATE.md
- Yes or No ? no
- If yes, which issue (fix #number) ?
- Yes or no ? no
Add some infos in issue template to ask
=> update issue template to get more info

CHANGELOG.md, package.json
- Yes
- Need merge to select version in npm
- No
Please, merge this commit for update npm version
Yes, its required for receive last updates
=> NPM Version

CHANGELOG.md, package.json
- Yes or No ?
- If yes, which issue (fix #number) ?
- Yes or no ?
=> Bump version 1.5.12 and update CHANGELOG.md

CHANGELOG.md, examples/package.json, examples/yarn.lock, package.json
- Yes or No ?
- If yes, which issue (fix #number) ?
- Yes or no ?
=> Bump version

src/index.js
* Solves https://github.com/leecade/react-native-swiper/issues/444
- Yes
- fix #444 
- no
=> Remove fontFamily: 'Arial'.

index.d.ts
Likely a copy/paste error. The timeout should be type `number` instead of `boolean`.
=> Correcting type `autoplayTimeout: number` prop

index.js.flow
@leecade Your package amaizing! Thank you :heart:
=> Add flow definitions

CHANGELOG.md, package.json
[1.5.14]
+ fixes #582 (Android not setting this onLayout first?) #789 (thanks [@fungilation](https://github.com/fungilation))
+ Add onScrollBegin and onTouchEnd for Android #684 (thanks [@kostyaVyrodov](https://github.com/kostyaVyrodov))
=> Release 1.5.14

CHANGELOG.md, README.md, package.json, src/index.js, yarn.lock
* build(ViewPagerAndroid): from react-native => @react-native-community/viewpager
* docs(v1.6.0-dev): update changelog and installation guide
re #988, re #981, re #951, re #923
=> build(ViewPagerAndroid): from react-native => @react-native-community/viewpager

index.d.ts, src/index.js
=> fix(types): correct the wrong types

index.js.flow
- Yes ?
- #899 ?
- No ?
Fixed flow type
run flow on the project
=> fixed flow typing

README.md
=> docs(nightly): add nightly version updates

package.json, src/index.js, yarn.lock
=> fix(types): allow the style to be array

src/index.js
=> fix(children): fix the crash when only one children
