leecade/react-native-swiper

dist/index.js, src/index.js
As noted in #82 the index prop can be used to maintain the index on state change. (Otherwise, a re-render resets the swiper to the initial position.) However, I noticed that this solution only works for me when loop={false}. The problem when loop={true} is the position of the swiper resets to the first child element.
Upon closer inspection, the index on the internal context is what it should be. The problems looks to be in the initState method the setup variable is always set to 1 when props.loop is true ( `var setup = props.loop ? 1 : initState.index;`).
I believe changing that line to the following will fix the issue.
```
var setup = initState.index
if ( props.loop ) {
setup++
}
```
=> fix for #97

dist/index.js, src/index.js
`react-native` as of `0.25.x` is deprecating `.cloneElement()` and `.createElement()`, instead suggesting we use those methods from the `react` package as opposed to `react-native`.
This commit fixes those warnings.
=> Fixed: warnings on react-native 0.25.x

README.md
I noticed that links to examples are broken. This fixes those and makes the readme a bit more useful.
=> Fixes broken links to examples in readme

dist/index.js, src/index.js
because `Dimensions.get('window').width` return a float number.
so when diff and step is float, especially on some Android devices, sometimes `parseInt` will not change index which should be correctly +1.
example:
```javascript
// test on Google Nexus 5X
const index = 0
const diff = 1237.2835597264346
const step = 412.427853242145 
// because (diff / step) will return 2.99999999999
parseInt(index + diff / step) //  will return 2 but expected to return 3
```
so I add `Math.round` try to solve this.
use `parseInt(index + Math.round(diff / step))` or  `Math.round(index + diff / step)`
=> fix float calculation  error

src/index.js
Just a small addition!
Simply turned
`let title = child && child.props.title`
to
`let title = child && child.props && child.props.title`
Because my app crashed when child.props turned out to be undefined.
=> Added extra check for title

src/index.js
There was a small typo in comments which said, the pagination will only be rendered if the 'total' was greater than 2, where it should have been greater than 1.
=> changed a small typo in comments

examples/components/SwiperNumber/index.js, src/index.js
The problem: After a swipe is complete and the offset is being set in the state, if you keep swiping you can potentially have the ScrollView's internal offset be different than the one you are setting in state. If this is the case, then when the render happens and the offset is passed in as a prop to ScrollView, then it resets the offset to the one specified. The result is that you can be mid-swipe and the pages will jump back partially to the old offset causing some nasty jitter.
The fix: I added this.internals to store calculated values that are used a lot and are passed back to callbacks, but do not directly effect the render (isScrolling and offset). Offset does effect rendering but should only effect it when the size changes or if total pages changes. So offset is stored in …
=> Fix jitter when quickly swiping back and forth between pages (iOS)

src/index.js
This fixes the issue of the swiper transitioning one more time after setting autoplay to false.
=> Disable autoplay timer when prop changes to false

README.md, src/index.js
There is now a simple way to listen to user's swipes.
I added a method `onIndexChanged` that is called with the new index everytime the user swipes. This allows, for example, to link this component to a Redux store.
Fixes #436
=> It is now possible to listen to index changes when user swipes

src/index.js
Prevent this crash : 
```
com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `int64', but had type `null'
at com.facebook.react.bridge.ReadableNativeMap.getInt(Native Method)
```
when using one of the latest release.
=> preventing apps using previous version to crash

package.json, src/index.js
- react-native-swiper v1.5.9
- react-native v0.44.3
Index page is displayed after render
First item is displayed, with paging showing correct dot highlighted.
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Create swiper that takes full width of page
2. Set non-zero index
3. Observe first page (with zero index) rendered as initial.
=> Fix iOS initial index issue && Bump version

src/index.js
Hello!
No
Yes
When I tap Dot in my Custom Pagination I need somehow to update index in Swiper. To show currently active Dot
Update index in Swiper component. It should return correct new index
=> update index when new index passed through props

src/index.js
Enables the inital index to be rendered first, avoiding a render of uncalculated offset.
- Yes
- [#540](https://github.com/leecade/react-native-swiper/issues/540) ?
- No
Calculate the offset of the index prop in the initial state.
Enables the initial index to be rendered first, avoiding a render of uncalculated offset.
Provide index prop >0.
=> Calculate the offset in the initial state instead of `onLayout`.

src/index.js
Relates to issue: https://github.com/leecade/react-native-swiper/issues/530
If something is off or I missed anything  just let me know, thanks!
=> Optionally disable the 'next' control button

src/index.js
As mentioned in [RN Docs](https://facebook.github.io/react-native/docs/stylesheet.html) `StyleSheet` are passed not as objects, but as numbers (references), due to performance reasons.
This change would disable annoying `PropTypes` warnings when `StyleSheet` is passed to `dotStyle` and `activeDotStyle`.
=> Allow dotStyle and activeDotStyle PropTypes to accept StyleSheet

src/index.js
when using https://github.com/flyskywhy/react-web
ref to https://facebook.github.io/react/docs/refs-and-the-dom.html
=> Fix `Uncaught TypeError: _this.refs.scrollView.scrollTo is not a function`

src/index.js
- Yes
- fix #570 
Just added a Swiper flag to track the initial render, and executed scrollView.scrollTo method with the appropriate offset.
* Use react 0.48.0 with default example from react-native-swiper README.
* it will reproduce the buggy behavior when contentOffset is not applied to ScrollView. (Last page will be displayed first.)
* Apply the current patch. The scrollView.scrollTo should scroll to proper offset on first 'onLayout' call of Swiper.
It is applied only if there are more than 1 slides.
=> Workaround for react-native 0.4.8 contentOffset regression

src/index.js
- Yes
- Issue (fix #36)
- I moved code that gets width and height to the initState() function
Precondition:
`
<Swiper
index={this.state.selectedPageIndex}
onIndexChanged={(index) => this.setState({ selectedPageIndex: index })}>
<SomeView/>
</Swiper>
`
- Add function to handle onIndexChanged
- Pass updatedIndex
Steps:
- Rotate device
- Swipe
=> Fix wrong calculation of width and height after device rotation

src/index.js
When swiper component is mounted, width and height are calculated and set in state. But if you change to another view in your app (in my case pressing on another tab, I'm using tabs from 'react-native-scrollable-tab-view'), the component is not unmounted, so if you come back to the view which contents swiper component, it is doing this:
`
initState.width = props.width || width // same with height
`
and it's not correct, because it should set previously calculated width and height, which is stored in state.
In my case, calculated height was 465 (correct, calculated by onLayout function), but when I came back height was set to 500 (incorrect, given by `const { width, height } = Dimensions.get('window')`)
I also needed to set style prop to ScrollView, so I added it.
=> Calculated width & height on layout, used later on re-rendering. Possibility to change ScrollView styles

src/index.js
Yes
https://github.com/leecade/react-native-swiper/issues/489
No
The swiper is now listening on Android ViewPagerAndroid's onPageScrollStateChanged event.
Just use onScrollBeginDrag.
=> Add onScrollBegin and onTouchEnd for Android

src/index.js
- No ?
- Yes
- scrollTo specific slider
scroll to specific slider
call scrollTo using a button, and swiper reference, using index as parameter (eg, using a toolbar on top)
=> added scrollTo

package.json, src/index.js
- Yes
- fix #989
- No
continue to play when this.props.autoplay is setted to true
```tsx
const SwiperComponent = () => {
const [autoPlay, setAutoPlay] = useState(true)
return (
<Swiper style={styles.wrapper} autoplay={autoPlay}>
<View style={styles.slide1}>
<TouchableWithoutFeedback onPress={() => setAutoPlay(false)}>
<Text style={styles.text}>Stop</Text>
</TouchableWithoutFeedback>
</View>
<View style={styles.slide2}>
<Text style={styles.text}>HHH</Text>
</View>
<View style={styles.slide3}>
<TouchableWithoutFeedback onPress={() => setAutoPlay(true)}>
<Text style={styles.text}>Start</Text>
</TouchableWithoutFeedback>
</View>
</Swiper>
)
}
```
autoPlay: true => false => true
=> fix(autoplay): replay when autoplay is setted to true

src/index.js
- Yes
- No
style can be array.
set dotStyles using array
```
<Swiper 
dotStyle={styles.scrollDotStyle}
activeDotStyle={[styles.scrollDotStyle,{ backgroundColor: '#686868'}]}>
```
=> add array to dotStyles propTypes

package.json, src/index.js
Extra: Remove @react-native-community/viewpager, use ScrollView on android
=> feat(pages): support optionally render page

index.d.ts
- Yes, issue #1035 
- No
Added a TypeScript definition for `scrollTo` to `index.d.ts`
```
import Swiper from 'react-native-swiper'
const swiper: Swiper = new Swiper({})
if (swiper) {
swiper.scrollTo(1, false)
}
```
This will now pass the TypeScript compiler whereas before it wouldn't
=> Add missing scrollTo TypeScript definition

index.d.ts
- Yes or No ? No
- If yes, which issue (fix #number) ? I didn't see an open issue for this
- Yes or no ? No (I don't think so)
In trying to do something along the lines of:
```tsx
const swiper = React.useRef<ReactNativeSwiper>(null);
React.useEffect(() => {
if (!swiper.current) {
return;
}
if (swiper.current.state.index !== indexOfNextQuestion) {
swiper.current.scrollBy(
indexOfNextQuestion - swiper.current.state.index,
true
);
}
```
TypeScript was saying "Property 'index' does not exist on type 'Readonly<{}>'." on `swiper.current.state.index`, even though the value was defined at runtime and these values appeared to be defined in state in the component's source code. 
In looking at the types, it looked like the state wasn't being passed to …
=> Pass State Types to Swiper Component

index.d.ts
Yes
No
Fixed mistakenly removed `}` whose absence caused
```
This missing `}` caused cause TypeScript error:
`node_modules/react-native-swiper/index.d.ts:147:1 - error TS1005: '}' expected.
```
Use in React and run Typescript compilation.
=> Fix React type declaration

src/index.js
- Yes or No ? Yes
- If yes, which issue (fix #number) ? #1192
- Yes or no ? No
Ensured that updateIndex does not result in a NaN when you scrollTo or scrollBy on mount
scrollTo or scrollBy on mount using a ref to the component
old version: nothing happens
new version: works
=> fix NaN on mount
